/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_DEMOPARTIALCLASSES
#define VCZH_WORKFLOW_COMPILER_GENERATED_DEMOPARTIALCLASSES

#include "GacUI.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace vl_workflow_global
{
	struct __vwsnf1_Demo_demo_LocalizedColorDialogTabPageConstructor___vwsn_demo_LocalizedColorDialogTabPage_Initialize_;
	struct __vwsnf3_Demo_demo_LocalizedFileDialogTabPageConstructor___vwsn_demo_LocalizedFileDialogTabPage_Initialize_;
	struct __vwsnf4_Demo_demo_LocalizedFileDialogTabPageConstructor___vwsn_demo_LocalizedFileDialogTabPage_Initialize_;
	struct __vwsnf5_Demo_demo_LocalizedFontDialogTabPageConstructor___vwsn_demo_LocalizedFontDialogTabPage_Initialize_;
	struct __vwsnf9_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_;
	struct __vwsno2_Demo_demo_LocalizedFileDialogTabPageConstructor___vwsn_demo_LocalizedFileDialogTabPage_Initialize_;
	struct __vwsno6_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_;
	struct __vwsno7_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_;
	struct __vwsno8_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_;
}

namespace demo
{
	class LocalizedColorDialogTabPageConstructor;
	class LocalizedColorDialogTabPage;
	class LocalizedFileDialogTabPageConstructor;
	class LocalizedFileDialogTabPage;
	class LocalizedFontDialogTabPageConstructor;
	class LocalizedFontDialogTabPage;
	class LocalizedMessageDialogTabPageConstructor;
	class LocalizedMessageDialogTabPage;
	class MainWindowConstructor;
	class MainWindow;

	class LocalizedColorDialogTabPageConstructor : public ::vl::Object, public ::vl::reflection::Description<LocalizedColorDialogTabPageConstructor>
	{
		friend struct ::vl_workflow_global::__vwsnf1_Demo_demo_LocalizedColorDialogTabPageConstructor___vwsn_demo_LocalizedColorDialogTabPage_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<LocalizedColorDialogTabPageConstructor>;
#endif
	protected:
		::demo::LocalizedColorDialogTabPage* self;
		::vl::presentation::controls::GuiColorDialog* dialog;
		::vl::Ptr<::vl::presentation::elements::GuiSolidBackgroundElement> background;
		::vl::presentation::compositions::GuiTableComposition* __vwsn_precompile_0;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_1;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_2;
		::vl::presentation::controls::GuiButton* __vwsn_precompile_3;
		void __vwsn_demo_LocalizedColorDialogTabPage_Initialize(::demo::LocalizedColorDialogTabPage* __vwsn_this_);
	public:
		LocalizedColorDialogTabPageConstructor();
	};

	class LocalizedColorDialogTabPage : public ::vl::presentation::controls::GuiTabPage, public ::demo::LocalizedColorDialogTabPageConstructor, public ::vl::reflection::Description<LocalizedColorDialogTabPage>
	{
		friend class ::demo::LocalizedColorDialogTabPageConstructor;
		friend struct ::vl_workflow_global::__vwsnf1_Demo_demo_LocalizedColorDialogTabPageConstructor___vwsn_demo_LocalizedColorDialogTabPage_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<LocalizedColorDialogTabPage>;
#endif
	public:
		LocalizedColorDialogTabPage();
		~LocalizedColorDialogTabPage();
	};

	class LocalizedFileDialogTabPageConstructor : public ::vl::Object, public ::vl::reflection::Description<LocalizedFileDialogTabPageConstructor>
	{
		friend struct ::vl_workflow_global::__vwsnf3_Demo_demo_LocalizedFileDialogTabPageConstructor___vwsn_demo_LocalizedFileDialogTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf4_Demo_demo_LocalizedFileDialogTabPageConstructor___vwsn_demo_LocalizedFileDialogTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsno2_Demo_demo_LocalizedFileDialogTabPageConstructor___vwsn_demo_LocalizedFileDialogTabPage_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<LocalizedFileDialogTabPageConstructor>;
#endif
	protected:
		::demo::LocalizedFileDialogTabPage* self;
		::vl::presentation::controls::GuiSinglelineTextBox* txtTitle;
		::vl::presentation::controls::GuiOpenFileDialog* dialogOpen;
		::vl::presentation::controls::GuiSaveFileDialog* dialogSave;
		::vl::presentation::controls::GuiSinglelineTextBox* txtDirectory;
		::vl::presentation::controls::GuiSinglelineTextBox* txtFileName;
		::vl::presentation::controls::GuiSinglelineTextBox* txtFilter;
		::vl::presentation::controls::GuiSinglelineTextBox* txtFilterIndex;
		::vl::presentation::controls::GuiSinglelineTextBox* txtDefaultExtension;
		::vl::presentation::controls::GuiSelectableButton* chkFileDialogAllowMultipleSelection;
		::vl::presentation::controls::GuiSelectableButton* chkFileDialogFileMustExist;
		::vl::presentation::controls::GuiSelectableButton* chkFileDialogShowReadOnlyCheckBox;
		::vl::presentation::controls::GuiSelectableButton* chkFileDialogDereferenceLinks;
		::vl::presentation::controls::GuiSelectableButton* chkFileDialogShowNetworkButton;
		::vl::presentation::controls::GuiSelectableButton* chkFileDialogPromptCreateFile;
		::vl::presentation::controls::GuiSelectableButton* chkFileDialogPromptOverwriteFile;
		::vl::presentation::controls::GuiSelectableButton* chkFileDialogDirectoryMustExist;
		::vl::presentation::controls::GuiSelectableButton* chkFileDialogAddToRecent;
		::vl::presentation::controls::GuiBindableTextList* lstFiles;
		::vl::presentation::compositions::GuiStackComposition* __vwsn_precompile_0;
		::vl::presentation::compositions::GuiStackItemComposition* __vwsn_precompile_1;
		::vl::presentation::compositions::GuiTableComposition* __vwsn_precompile_2;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_3;
		::vl::presentation::controls::GuiLabel* __vwsn_precompile_4;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_5;
		::vl::presentation::controls::GuiLabel* __vwsn_precompile_6;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_7;
		::vl::presentation::controls::GuiLabel* __vwsn_precompile_8;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_9;
		::vl::presentation::controls::GuiLabel* __vwsn_precompile_10;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_11;
		::vl::presentation::controls::GuiLabel* __vwsn_precompile_12;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_13;
		::vl::presentation::controls::GuiLabel* __vwsn_precompile_14;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_15;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_16;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_17;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_18;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_19;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_20;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_21;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_22;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_23;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_24;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_25;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_26;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_27;
		::vl::presentation::compositions::GuiStackComposition* __vwsn_precompile_28;
		::vl::presentation::compositions::GuiStackItemComposition* __vwsn_precompile_29;
		::vl::presentation::compositions::GuiStackItemComposition* __vwsn_precompile_30;
		::vl::presentation::compositions::GuiStackItemComposition* __vwsn_precompile_31;
		::vl::presentation::compositions::GuiStackItemComposition* __vwsn_precompile_32;
		::vl::presentation::compositions::GuiStackItemComposition* __vwsn_precompile_33;
		::vl::presentation::compositions::GuiStackItemComposition* __vwsn_precompile_34;
		::vl::presentation::compositions::GuiStackItemComposition* __vwsn_precompile_35;
		::vl::presentation::compositions::GuiStackItemComposition* __vwsn_precompile_36;
		::vl::presentation::compositions::GuiStackItemComposition* __vwsn_precompile_37;
		::vl::presentation::compositions::GuiStackItemComposition* __vwsn_precompile_38;
		::vl::presentation::controls::GuiLabel* __vwsn_precompile_39;
		::vl::presentation::compositions::GuiStackItemComposition* __vwsn_precompile_40;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_41;
		::vl::presentation::compositions::GuiStackItemComposition* __vwsn_precompile_42;
		::vl::presentation::compositions::GuiStackComposition* __vwsn_precompile_43;
		::vl::presentation::compositions::GuiStackItemComposition* __vwsn_precompile_44;
		::vl::presentation::controls::GuiButton* __vwsn_precompile_45;
		::vl::presentation::compositions::GuiStackItemComposition* __vwsn_precompile_46;
		::vl::presentation::controls::GuiButton* __vwsn_precompile_47;
		void __vwsn_demo_LocalizedFileDialogTabPage_Initialize(::demo::LocalizedFileDialogTabPage* __vwsn_this_);
	public:
		LocalizedFileDialogTabPageConstructor();
	};

	class LocalizedFileDialogTabPage : public ::vl::presentation::controls::GuiTabPage, public ::demo::LocalizedFileDialogTabPageConstructor, public ::vl::reflection::Description<LocalizedFileDialogTabPage>
	{
		friend class ::demo::LocalizedFileDialogTabPageConstructor;
		friend struct ::vl_workflow_global::__vwsnf3_Demo_demo_LocalizedFileDialogTabPageConstructor___vwsn_demo_LocalizedFileDialogTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf4_Demo_demo_LocalizedFileDialogTabPageConstructor___vwsn_demo_LocalizedFileDialogTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsno2_Demo_demo_LocalizedFileDialogTabPageConstructor___vwsn_demo_LocalizedFileDialogTabPage_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<LocalizedFileDialogTabPage>;
#endif
	public:
		void SetDialogProperties(::vl::presentation::controls::GuiFileDialogBase* dialog);
		LocalizedFileDialogTabPage();
		~LocalizedFileDialogTabPage();
	};

	class LocalizedFontDialogTabPageConstructor : public ::vl::Object, public ::vl::reflection::Description<LocalizedFontDialogTabPageConstructor>
	{
		friend struct ::vl_workflow_global::__vwsnf5_Demo_demo_LocalizedFontDialogTabPageConstructor___vwsn_demo_LocalizedFontDialogTabPage_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<LocalizedFontDialogTabPageConstructor>;
#endif
	protected:
		::demo::LocalizedFontDialogTabPage* self;
		::vl::presentation::controls::GuiFontDialog* dialog;
		::vl::Ptr<::vl::presentation::elements::GuiSolidLabelElement> label;
		::vl::presentation::controls::GuiSelectableButton* checkEffect;
		::vl::presentation::compositions::GuiTableComposition* __vwsn_precompile_0;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_1;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_2;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_3;
		::vl::presentation::controls::GuiButton* __vwsn_precompile_4;
		void __vwsn_demo_LocalizedFontDialogTabPage_Initialize(::demo::LocalizedFontDialogTabPage* __vwsn_this_);
	public:
		LocalizedFontDialogTabPageConstructor();
	};

	class LocalizedFontDialogTabPage : public ::vl::presentation::controls::GuiTabPage, public ::demo::LocalizedFontDialogTabPageConstructor, public ::vl::reflection::Description<LocalizedFontDialogTabPage>
	{
		friend class ::demo::LocalizedFontDialogTabPageConstructor;
		friend struct ::vl_workflow_global::__vwsnf5_Demo_demo_LocalizedFontDialogTabPageConstructor___vwsn_demo_LocalizedFontDialogTabPage_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<LocalizedFontDialogTabPage>;
#endif
	public:
		LocalizedFontDialogTabPage();
		~LocalizedFontDialogTabPage();
	};

	class LocalizedMessageDialogTabPageConstructor : public ::vl::Object, public ::vl::reflection::Description<LocalizedMessageDialogTabPageConstructor>
	{
		friend struct ::vl_workflow_global::__vwsnf9_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsno6_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsno7_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsno8_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<LocalizedMessageDialogTabPageConstructor>;
#endif
	protected:
		::demo::LocalizedMessageDialogTabPage* self;
		::vl::presentation::controls::GuiMessageDialog* dialog;
		::vl::presentation::controls::GuiSinglelineTextBox* txtTitle;
		::vl::presentation::controls::GuiSinglelineTextBox* txtText;
		::vl::presentation::controls::GuiComboBoxListControl* comboInput;
		::vl::presentation::controls::GuiComboBoxListControl* comboDefaultButton;
		::vl::presentation::controls::GuiComboBoxListControl* comboIcon;
		::vl::presentation::controls::GuiLabel* lblOutput;
		::vl::presentation::compositions::GuiTableComposition* __vwsn_precompile_0;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_1;
		::vl::presentation::controls::GuiLabel* __vwsn_precompile_2;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_3;
		::vl::presentation::controls::GuiLabel* __vwsn_precompile_4;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_5;
		::vl::presentation::controls::GuiLabel* __vwsn_precompile_6;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_7;
		::vl::presentation::controls::GuiLabel* __vwsn_precompile_8;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_9;
		::vl::presentation::controls::GuiLabel* __vwsn_precompile_10;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_11;
		::vl::presentation::controls::GuiLabel* __vwsn_precompile_12;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_13;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_14;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_15;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_16;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_17;
		::vl::presentation::controls::GuiBindableTextList* __vwsn_precompile_18;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_19;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_20;
		::vl::presentation::controls::GuiBindableTextList* __vwsn_precompile_21;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_22;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_23;
		::vl::presentation::controls::GuiBindableTextList* __vwsn_precompile_24;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_25;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_26;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_27;
		::vl::presentation::controls::GuiButton* __vwsn_precompile_28;
		void __vwsn_demo_LocalizedMessageDialogTabPage_Initialize(::demo::LocalizedMessageDialogTabPage* __vwsn_this_);
	public:
		LocalizedMessageDialogTabPageConstructor();
	};

	class LocalizedMessageDialogTabPage : public ::vl::presentation::controls::GuiTabPage, public ::demo::LocalizedMessageDialogTabPageConstructor, public ::vl::reflection::Description<LocalizedMessageDialogTabPage>
	{
		friend class ::demo::LocalizedMessageDialogTabPageConstructor;
		friend struct ::vl_workflow_global::__vwsnf9_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsno6_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsno7_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsno8_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<LocalizedMessageDialogTabPage>;
#endif
	public:
		::vl::Ptr<::vl::reflection::description::IValueList> inputValues;
		::vl::Ptr<::vl::reflection::description::IValueList> inputTexts;
		::vl::Ptr<::vl::reflection::description::IValueList> defaultButtonValues;
		::vl::Ptr<::vl::reflection::description::IValueList> defaultButtonTexts;
		::vl::Ptr<::vl::reflection::description::IValueList> iconValues;
		::vl::Ptr<::vl::reflection::description::IValueList> iconTexts;
		::vl::Ptr<::vl::reflection::description::IValueList> outputValues;
		::vl::Ptr<::vl::reflection::description::IValueList> outputTexts;
		LocalizedMessageDialogTabPage();
		void __vwsn_instance_ctor_();
		~LocalizedMessageDialogTabPage();
	};

	class MainWindowConstructor : public ::vl::Object, public ::vl::reflection::Description<MainWindowConstructor>
	{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<MainWindowConstructor>;
#endif
	protected:
		::demo::MainWindow* self;
		::vl::presentation::controls::GuiTab* __vwsn_precompile_0;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_1;
		::demo::LocalizedMessageDialogTabPage* __vwsn_precompile_2;
		::demo::LocalizedColorDialogTabPage* __vwsn_precompile_3;
		::demo::LocalizedFontDialogTabPage* __vwsn_precompile_4;
		::demo::LocalizedFileDialogTabPage* __vwsn_precompile_5;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_6;
		void __vwsn_demo_MainWindow_Initialize(::demo::MainWindow* __vwsn_this_);
	public:
		MainWindowConstructor();
	};

	class MainWindow : public ::vl::presentation::controls::GuiWindow, public ::demo::MainWindowConstructor, public ::vl::reflection::Description<MainWindow>
	{
		friend class ::demo::MainWindowConstructor;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<MainWindow>;
#endif
	public:
		MainWindow();
		~MainWindow();
	};

}
/***********************************************************************
Global Variables and Functions
***********************************************************************/

namespace vl_workflow_global
{
	class Demo
	{
	public:

		static Demo& Instance();
	};

/***********************************************************************
Closures
***********************************************************************/

	struct __vwsnf1_Demo_demo_LocalizedColorDialogTabPageConstructor___vwsn_demo_LocalizedColorDialogTabPage_Initialize_
	{
		::demo::LocalizedColorDialogTabPageConstructor* __vwsnthis_0;

		__vwsnf1_Demo_demo_LocalizedColorDialogTabPageConstructor___vwsn_demo_LocalizedColorDialogTabPage_Initialize_(::demo::LocalizedColorDialogTabPageConstructor* __vwsnctorthis_0);

		void operator()(::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments) const;
	};

	struct __vwsnf3_Demo_demo_LocalizedFileDialogTabPageConstructor___vwsn_demo_LocalizedFileDialogTabPage_Initialize_
	{
		::demo::LocalizedFileDialogTabPageConstructor* __vwsnthis_0;

		__vwsnf3_Demo_demo_LocalizedFileDialogTabPageConstructor___vwsn_demo_LocalizedFileDialogTabPage_Initialize_(::demo::LocalizedFileDialogTabPageConstructor* __vwsnctorthis_0);

		void operator()(::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments) const;
	};

	struct __vwsnf4_Demo_demo_LocalizedFileDialogTabPageConstructor___vwsn_demo_LocalizedFileDialogTabPage_Initialize_
	{
		::demo::LocalizedFileDialogTabPageConstructor* __vwsnthis_0;

		__vwsnf4_Demo_demo_LocalizedFileDialogTabPageConstructor___vwsn_demo_LocalizedFileDialogTabPage_Initialize_(::demo::LocalizedFileDialogTabPageConstructor* __vwsnctorthis_0);

		void operator()(::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments) const;
	};

	struct __vwsnf5_Demo_demo_LocalizedFontDialogTabPageConstructor___vwsn_demo_LocalizedFontDialogTabPage_Initialize_
	{
		::demo::LocalizedFontDialogTabPageConstructor* __vwsnthis_0;

		__vwsnf5_Demo_demo_LocalizedFontDialogTabPageConstructor___vwsn_demo_LocalizedFontDialogTabPage_Initialize_(::demo::LocalizedFontDialogTabPageConstructor* __vwsnctorthis_0);

		void operator()(::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments) const;
	};

	struct __vwsnf9_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_
	{
		::demo::LocalizedMessageDialogTabPageConstructor* __vwsnthis_0;

		__vwsnf9_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_(::demo::LocalizedMessageDialogTabPageConstructor* __vwsnctorthis_0);

		void operator()(::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments) const;
	};

	struct __vwsno2_Demo_demo_LocalizedFileDialogTabPageConstructor___vwsn_demo_LocalizedFileDialogTabPage_Initialize_
	{
		::demo::LocalizedFileDialogTabPageConstructor* __vwsnthis_0;

		__vwsno2_Demo_demo_LocalizedFileDialogTabPageConstructor___vwsn_demo_LocalizedFileDialogTabPage_Initialize_(::demo::LocalizedFileDialogTabPageConstructor* __vwsnctorthis_0);

		::vl::WString operator()(const ::vl::reflection::description::Value& __vwsno_1) const;
	};

	struct __vwsno6_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_
	{
		::demo::LocalizedMessageDialogTabPageConstructor* __vwsnthis_0;

		__vwsno6_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_(::demo::LocalizedMessageDialogTabPageConstructor* __vwsnctorthis_0);

		::vl::WString operator()(const ::vl::reflection::description::Value& __vwsno_1) const;
	};

	struct __vwsno7_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_
	{
		::demo::LocalizedMessageDialogTabPageConstructor* __vwsnthis_0;

		__vwsno7_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_(::demo::LocalizedMessageDialogTabPageConstructor* __vwsnctorthis_0);

		::vl::WString operator()(const ::vl::reflection::description::Value& __vwsno_1) const;
	};

	struct __vwsno8_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_
	{
		::demo::LocalizedMessageDialogTabPageConstructor* __vwsnthis_0;

		__vwsno8_Demo_demo_LocalizedMessageDialogTabPageConstructor___vwsn_demo_LocalizedMessageDialogTabPage_Initialize_(::demo::LocalizedMessageDialogTabPageConstructor* __vwsnctorthis_0);

		::vl::WString operator()(const ::vl::reflection::description::Value& __vwsno_1) const;
	};
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
